// This file has been autogenerated from a class added in the UI designer.

using ScanbotSDK.iOS;

namespace ClassicComponent.iOS
{
    interface IVINScannerDelegate
    {
        void ShowResult(string result);
    }
    
    public partial class VINScannerViewController : UIViewController, IVINScannerDelegate
    {
        SBSDKVINScannerViewController vinScannerController;
        public VINScannerViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            var configuration = SBSDKVehicleIdentificationNumberScannerConfiguration.DefaultConfiguration;
            vinScannerController = new SBSDKVINScannerViewController(parentViewController: this,
                                                              parentView: containerView,
                                                              configuration: configuration,
                                                              new VINScannerDelegate(this));
        }

        public void ShowResult(string result)
        {
            lblResult.Text = result;
        }
    }

    internal class VINScannerDelegate : SBSDKVINScannerViewControllerDelegate
    {
        private IVINScannerDelegate scannerDelegate;

        public VINScannerDelegate(IVINScannerDelegate scannerDelegate)
        {
            this.scannerDelegate = scannerDelegate;
        }

        public override void DidScanValidResult(SBSDKVINScannerViewController controller, SBSDKVehicleIdentificationNumberScannerResult result)
        {
            scannerDelegate?.ShowResult(result.Text);
        }
    }
}
