// This file has been autogenerated from a class added in the UI designer.

using ScanbotSDK.iOS;

namespace ClassicComponent.iOS
{
    public interface IVinScannerDelegate
    {
        void ShowResult(string result);
    }
    
    public partial class VINScannerViewController : UIViewController, IVinScannerDelegate
    {
        private SBSDKVINScannerViewController _vinScannerController;
        public VINScannerViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            var configuration = new SBSDKVINScannerConfiguration();
            _vinScannerController = new SBSDKVINScannerViewController(parentViewController: this,
                                                              parentView: containerView,
                                                              configuration: configuration,
                                                              new VinScannerDelegate(this));
        }

        public void ShowResult(string result)
        {
            lblResult.Text = result;
        }
    }

    public class VinScannerDelegate(IVinScannerDelegate scannerDelegate) : SBSDKVINScannerViewControllerDelegate
    {
        public override void DidScanValidResult(SBSDKVINScannerViewController controller, SBSDKVINScannerResult result)
        {
            scannerDelegate?.ShowResult(result.TextResult.RawText);
        }
    }
}
